name: Build example - Linux Standalone

on:
    # push:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true

jobs:
    linux_standalone:
        name: Linux Standalone
        timeout-minutes: 90

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: connectedhomeip/chip-build:0.6.18
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              submodules: recursive
              
          - name: Checkout submodules
            run: scripts/checkout_submodules.py --shallow --platform linux